### ISSUE TITLE
next() does not implement predicate function

### ISSUE THREAD

**Issue by crunchie84** [kwonoj/rxjs-testscheduler-compat#31]
First, thanks for your efforts to create this rxjs4 => rxjs5 testing migration tool. It really helps to get my codebase upgraded towards RxJs5

In some of my tests i rely on the [predicate implementation of `onNext()`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/testing/reactivetest.js#L31-L36) because the elements emitted are big and i only care to validate a few properties. 

This implementation seems to be absent in `rxjs-testscheduler-compat@0.0.4`

**Comment by crunchie84** [comment]
It seems that since the value of `next()` is `any` i'm able to just embed a predicate in it (`next(100, evt =>evt.value.innerProp === 'foo')`) and use the following to evaluate after running if it is true:

```
if (e.notification.value && typeof e.notification.value === 'function') {
  isOk = e.time === a.time && e.notification.value(a.notification);
}
```

For reference I have cobbled together the following comparison function to do RxJs4 (and with this compat package RxJs5) tests: https://gist.github.com/crunchie84/82dc64060dcb429704d8beb03e3a1d9b

**Comment by crunchie84** [comment]
Maybe not really a bug but undocumented behaviour after all?

**Comment by kwonoj** [comment]
Yes, I wouldn't say it's bug. Also this impl intend naïve coverage to v4's api surfaces, might have some missing one like this. Will see if I can cover this up though.

**Comment by kwonoj** [comment]
I've been thought about this bit and decided to leave as status quo, while it doesn't explicitly supports it but still allowed to use undocumented way. Probably will leave as tip in documentation if this behavior is needed, but doesn't strongly feel to implement explicitly at this moment. Still huge appreciate to point out this.

**Comment by kwonoj** [comment]
And just clarify, if there's usecases this may needed, can be revisited further.
