### ISSUE TITLE
Not compatible with RxJS 5.2.0

### ISSUE THREAD

**Issue by meenie** [kwonoj/rxjs-testscheduler-compat#36]
Getting following error when compiling:
```
node_modules/@kwonoj/rxjs-testscheduler-compat/dist/src/VirtualPromise.d.ts(6,22): error TS2420: Class 'BaseVirtualPromise' incorrectly implements interface 'VirtualPromise'.
  Property '[Symbol.toStringTag]' is missing in type 'BaseVirtualPromise'.
```

**Comment by kwonoj** [comment]
Would you mind share minimal repo to try this out? I hve feeling this might be by missing some type definition pkgs

**Comment by kwonoj** [comment]
check https://github.com/kwonoj/testscheduler-setup-example and build passing at https://travis-ci.org/kwonoj/testscheduler-setup-example/builds/206065654.

**Comment by kwonoj** [comment]
above repo will be deleted after some time.
